apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-persistence-container
  labels:
    app: tech-challenge-persistence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-persistence
  template:
    metadata:
      labels:
        app: tech-challenge-persistence
    spec:
      containers:
      - name: tech-challenge-persistence
        image: "natanroberto182/tech-challenge-persistence:latest"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "HML"