apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-persistence-service
spec:
  selector:
    app: tech-challenge-persistence
  ports:
    - protocol: TCP
      port: 5207
      targetPort: 80
  type: LoadBalancer
