version: '3.8'

services:
  myapp:
    image: regionpersistence:latest
    container_name: regionpersistence_container
    ports:
      - "5203:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "HML"
    networks:
      - techchallengenetwork

networks:
  techchallengenetwork:
    external: true