version: '3.8'

services:
  myapp:
    image: userquery:latest
    container_name: userquery_container
    ports:
      - "5200:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "HML"
    networks:
      - techchallengenetwork

networks:
  techchallengenetwork:
    external: true