name: CI/CD for User Query

on:
  workflow_dispatch:

jobs:  
  build-and-push:
    name: Build, Test, and Publish Docker Images for Changed Services
    runs-on: NOTEBOOK-NATAN

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace appsettings for User Query
        run: |
          echo "Replacing appsettings for User Query"
          cmd /C "copy /Y c:\appsettings\appsettings.json %GITHUB_WORKSPACE%\Tech.Challenge.III.User.Query\User.Query\User.Query.Api\appsettings.json"
          cmd /C "copy /Y c:\appsettings\appsettings.Test.json %GITHUB_WORKSPACE%\Tech.Challenge.III.User.Query\User.Query\User.Query.Api\appsettings.Test.json"
          cmd /C "copy /Y c:\appsettings\appsettings.IntegrationTests.json %GITHUB_WORKSPACE%\Tech.Challenge.III.User.Query\User.Query\User.Query.Api\appsettings.IntegrationTests.json"

      - name: Restore dependencies
        run: |
          echo "Restoring dependencies for User Query"
          cd Tech.Challenge.III.User.Query/User.Query/
          dotnet restore

      - name: Build the User Query
        run: |
          echo "Building the User Query"
          dotnet build Tech.Challenge.III.User.Query/User.Query/User.Query.sln --no-restore --configuration Release

      - name: Run unit tests
        run: |
          echo "Running unit tests"
          dotnet test Tech.Challenge.III.User.Query/User.Query/User.Query.Tests/User.Query.Tests.csproj --no-build --configuration Release --logger "trx;LogFileName=unit-test-user-query-results.trx"

      - name: Run integration tests
        run: |
          echo "Running integration tests"
          dotnet test Tech.Challenge.III.User.Query/User.Query/User.Query.Integration.Tests/User.Query.Integration.Tests.csproj --no-build --configuration Release --logger "trx;LogFileName=integration-test-user-query-results.trx"
      
      - name: Login to Docker Hub
        run: |
          echo "Logging into Docker Hub"
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image for User Query
        run: |
          echo "Building and pushing Docker image for User Query"
          cd Tech.Challenge.III.User.Query/User.Query/
          IMAGE_NAME="natanroberto182/user-query:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  notify-config-repo:
    name: Notify Configurations Repository
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Set the list of services to notify
        id: services
        run: |
          echo "Determining which services were built successfully"
          services="user-query"
          echo "Services to notify: $services"
          echo "services=$services" >> $GITHUB_OUTPUT

      - name: Notify Configuration Repository
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.CONFIG_REPO_TOKEN }}" \
            -d '{"event_type": "update-configurations", "client_payload": {"services": "user-query"}}' \
            https://api.github.com/repos/natanrobertoxavier/Tech.Challenge.III.Config.Repo/dispatches